---
title: "Celiac_Phage_orf_oldAssembly_saveData"
output: html_document
date: "2025-10-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table);packageVersion("data.table")
library(tidyverse);packageVersion("tidyverse")
library(ggplot2);packageVersion("ggplot2")
library(broom);packageVersion("broom")
library(vroom);packageVersion("vroom")
library(limma);packageVersion("limma")
library(edgeR);packageVersion("edgeR")
library(pheatmap);packageVersion("pheatmap")
library(survival);packageVersion("survival")
library(ggpubr);packageVersion("ggpubr")


```



# load metadata
```{r}

metadata <- read.csv("~/Handley Lab Dropbox/16S/Celiac/metadata/Updated_Metadata_with_Onset_Timeline.csv") %>%
            select(-Sample.Name.External.ID) %>%
            select(-Classification) %>%
            #mutate(Onset_timepoint = ifelse(Onset.Dx < 30,"pre_30","post_30")) %>%
            column_to_rownames("X")
dim(metadata)
# 335  24


```


# load phrog table
```{r}

# remember to filter out NA but keep "NO_PHTOG"
phrog <- read_delim("~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/phold_per_cds_predictions.tsv") %>%
         select(`cds_id`,`phrog`) %>%
         column_to_rownames("cds_id") %>%
         filter(!is.na(phrog))

phrog

```




# 75% mapping rate filtering and 3% prevlance filtering on total data
```{r}


orf.processed <- readRDS("~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/total/wide_rpkm_genes_75Cov.rds") %>%
                 column_to_rownames("ORFID")

phrog.map <- orf.processed,phrog


# then let's check colSums and ensure there is no sample have all 0s across orfs
sample_all_0 <- names(colSums(orf.processed)[colSums(orf.processed) == 0])
# [1] "NovaSeq_N978_I13149_39572_Celiac_Leonard_Stool_01_GEMM_093_24M"      
# [2] "NovaSeq_N978_I13150_39573_Celiac_Leonard_Stool_01_GEMM_093_30M"      
# [3] "NovaSeq_N978_I13151_39574_Celiac_Leonard_Stool_01_GEMM_093_36M"      
# [4] "NovaSeq_N978_I13152_39575_Celiac_Leonard_Stool_01_GEMM_093_48M"      
# [5] "NovaSeq_N982_I13323_39837_Celiac_Leonard_Stool_02_GEMM_077_12M"      
# [6] "NovaSeq_N983_I13417_39799_Leonard_Human_stool_Celiac_02_GEMM_006_60M"


# let's remove the 6 0 counts samples
orf.processed <- orf.processed %>%
                    select(-all_of(sample_all_0))
dim(orf.processed)
# 47727   334


# here we found two duplicated samples:
# "NovaSeq_N978_I13164_39587_Celiac_Leonard_Stool_01_GEMM_106_12M_stats" and  "NovaSeq_N983_I13413_39587_Celiac_Leonard_Stool_01_GEMM_106_12M_stats"
# after checking with my note, the N983 01_GEMM_106_12M sample should actually be water
orf.processed <- orf.processed %>%
                 select(-NovaSeq_N983_I13413_39587_Celiac_Leonard_Stool_01_GEMM_106_12M)
dim(orf.processed)
# 47727   333

orf.count <- orf.processed

colnames(orf.count) <- gsub("NovaSeq_N966_|NovaSeq_N978_|NovaSeq_N979_|NovaSeq_N980_|NovaSeq_N981_|NovaSeq_N982_|NovaSeq_N983_|_stats","",colnames(orf.count))

colnames(orf.count) <- str_replace_all(colnames(orf.count),"Leonard_Human_stool_Celiac","Celiac_Leonard_Stool")
colnames(orf.count) <- sapply(strsplit(colnames(orf.count),"_Stool_|_Stool_Celiac_"),"[",2)
colnames(orf.count) <- ifelse(colnames(orf.count) %like% "_6Y",gsub("_6Y","_72M",colnames(orf.count)),
                                           ifelse(colnames(orf.count) %like% "_7Y",gsub("_7Y","_84M",colnames(orf.count)),colnames(orf.count)))

orf.count.table_0.75 <- t(orf.count) 
dim(orf.count.table_0.75)
# 333 47727


orf.abundance.table_0.75 <- merge(metadata,orf.count.table_0.75,by = 0) %>% # 329 samples left
                              filter(feeding_first_year != "Unknown") %>%  # 312 samples left
                              filter(Age.at.Gluten.Introduction..months. != "Unknown") # 308 sample left
dim(orf.abundance.table_0.75)
# 308 samples x  47752 metadata+orfs

all_0_contigs <- names(colSums(orf.abundance.table_0.75[25:47752])[colSums(orf.abundance.table_0.75[25:47752]) == 0])
# 830 contigs become 0 through all samples after the 25 samples were removed from the above step
# so we need to remove those contigs

orf.abundance.table_0.75 <- orf.abundance.table_0.75 %>%
                            select(-all_of(all_0_contigs))
dim(orf.abundance.table_0.75)
# 308 samples x 46922 metadata+orfs
# 46897 orfs

orf.abundance.table <- orf.abundance.table_0.75 %>%
                       select(c("Row.names",26:46922)) %>%
                       column_to_rownames("Row.names") %>% 
                       t(.) %>%
                       data.frame(.)
colnames(orf.abundance.table) <- gsub("X","",colnames(orf.abundance.table))


# check prevelence filtering
prevalence <- rowSums(orf.abundance.table > 0) / ncol(orf.abundance.table)
table(prevalence > 0.03)  # 3% threshold
# FALSE  TRUE 
# 44478  2419

# Filter ORFs with prevalence > 3%
orf.abundance.clean <- orf.abundance.table[prevalence > 0.03, ]
      
dim(orf.abundance.clean)
# 2419  308 (3% prev)

# check if there are any samples become 0 counts
names(colSums(orf.abundance.clean)[colSums(orf.abundance.clean) == 0])
# "01_GEMM_154_30M" "02_GEMM_021_36M"

# remove the two 0 counts samples
# we will have to remove sample 02_GEMM_021_36M because it becomes 0 counts at this step
orf.abundance.clean <- orf.abundance.clean %>%
                       select(-c("01_GEMM_154_30M","02_GEMM_021_36M"))
dim(orf.abundance.clean)
# 2419  306


write.csv(orf.abundance.clean,"~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/total/total.orf.abundance.clean_0.75_0.03.csv",quote = FALSE,row.names = TRUE)


metadata.clean <- orf.abundance.table_0.75[1:25] %>%
                  filter(!Row.names %in% c("01_GEMM_154_30M","02_GEMM_021_36M")) %>%
                  column_to_rownames("Row.names")
dim(metadata.clean)
# 306  24

write.csv(metadata.clean,"~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/total/total.orf.metadata.clean_0.75_0.03.csv",quote = FALSE,row.names = TRUE)

# check if the column names of abundance table match the order of the row names of metadata table
all(rownames(metadata.clean) == colnames(orf.abundance.clean))
# TRUE

count_matrix <- as.matrix(orf.abundance.clean[, sapply(orf.abundance.clean, is.numeric)])
sparsity <- sum(count_matrix == 0) / length(count_matrix)
# 0.9521125

```



# 75% mapping rate filtering and 3% prevlance filtering on US
```{r}


# here we found two duplicated samples:
# "NovaSeq_N978_I13164_39587_Celiac_Leonard_Stool_01_GEMM_106_12M_stats" and  "NovaSeq_N983_I13413_39587_Celiac_Leonard_Stool_01_GEMM_106_12M_stats"
# after checking with my note, the N983 01_GEMM_106_12M sample should actually be water
# so we will just remove it
US_orf.processed <- readRDS("~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/US/wide_rpkm_genes_75Cov.rds") %>%
                   column_to_rownames("ORFID") %>%
                   select(-NovaSeq_N983_I13413_39587_Celiac_Leonard_Stool_01_GEMM_106_12M)
dim(US_orf.processed)
# 36851   207

US_sample_all_0 <- names(colSums(US_orf.processed)[colSums(US_orf.processed) == 0])
# [1] "NovaSeq_N978_I13149_39572_Celiac_Leonard_Stool_01_GEMM_093_24M"
# [2] "NovaSeq_N978_I13150_39573_Celiac_Leonard_Stool_01_GEMM_093_30M"
# [3] "NovaSeq_N978_I13151_39574_Celiac_Leonard_Stool_01_GEMM_093_36M"
# [4] "NovaSeq_N978_I13152_39575_Celiac_Leonard_Stool_01_GEMM_093_48M"


US.orf.count <- US_orf.processed %>%
                   select(-all_of(c(US_sample_all_0))) 
dim(US.orf.count)
# 36851   203

colnames(US.orf.count) <- gsub("NovaSeq_N966_|NovaSeq_N978_|NovaSeq_N979_|NovaSeq_N980_|NovaSeq_N981_|NovaSeq_N982_|NovaSeq_N983_|_stats","",colnames(US.orf.count))
colnames(US.orf.count) <- str_replace_all(colnames(US.orf.count),"Leonard_Human_stool_Celiac","Celiac_Leonard_Stool")
colnames(US.orf.count) <- sapply(strsplit(colnames(US.orf.count),"_Stool_|_Stool_Celiac_"),"[",2)
colnames(US.orf.count) <- ifelse(colnames(US.orf.count) %like% "_6Y",gsub("_6Y","_72M",colnames(US.orf.count)),
                                           ifelse(colnames(US.orf.count) %like% "_7Y",gsub("_7Y","_84M",colnames(US.orf.count)),colnames(US.orf.count)))

US.orf.count.table_0.75 <- t(US.orf.count) 
dim(US.orf.count.table_0.75)
# 203 36851


US.orf.abundance.table_0.75 <- merge(metadata,US.orf.count.table_0.75,by = 0) %>% # 201 samples left
                              filter(feeding_first_year != "Unknown") %>%  # 201 samples left
                              filter(Age.at.Gluten.Introduction..months. != "Unknown") # 197 sample left
# 197 samples x  36876 metadata+orfs
dim(US.orf.abundance.table_0.75)


US.all_0_contigs <- names(colSums(US.orf.abundance.table_0.75[25:36876])[colSums(US.orf.abundance.table_0.75[25:36876]) == 0])
length(US.all_0_contigs)
# 416 contigs become 0 through all samples after the 6 samples were removed from the above step
# so we need to remove those contigs

US.orf.abundance.table_0.75 <- US.orf.abundance.table_0.75 %>%
                            select(-all_of(US.all_0_contigs))
dim(US.orf.abundance.table_0.75)
# 197 samples x 36460 metadata+orfs
# 36435 orfs

US.orf.abundance.table <- US.orf.abundance.table_0.75 %>%
                       select(c("Row.names",26:36460)) %>%
                       column_to_rownames("Row.names") %>% 
                       t(.) %>%
                       data.frame(.)
colnames(US.orf.abundance.table) <- gsub("X","",colnames(US.orf.abundance.table))


# check prevelence filtering
prevalence <- rowSums(US.orf.abundance.table > 0) / ncol(US.orf.abundance.table)
table(prevalence > 0.03)  
# FALSE  TRUE 
# 32376  4059

# Filter ORFs with prevalence > 3%
US.orf.abundance.table <- US.orf.abundance.table[prevalence > 0.03, ]
      
dim(US.orf.abundance.table)
# 4059  197

# check if there are any samples become 0 counts
names(colSums(US.orf.abundance.table)[colSums(US.orf.abundance.table) == 0])
# 0

US.orf.abundance.clean <- US.orf.abundance.table
dim(US.orf.abundance.clean)
# 4059  197


write.csv(US.orf.abundance.clean,"~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/US/US.orf.abundance.clean_0.75_0.03.csv",quote = FALSE,row.names = TRUE)


US.metadata.clean <- US.orf.abundance.table_0.75[1:25] %>%
                     mutate(Onset_timepoint = ifelse(Onset.Dx < 30,"pre_30","post_30")) %>%
                     column_to_rownames("Row.names")
# 197  25



write.csv(US.metadata.clean,"~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/US/US.orf.metadata.clean_0.75_0.03.csv",quote = FALSE,row.names = TRUE)



# check if the column names of abundance table match the order of the row names of metadata table
all(rownames(US.metadata.clean) == colnames(US.orf.abundance.clean))
# TRUE

# check total sparsity
count_matrix <- as.matrix(US.orf.abundance.clean[, sapply(US.orf.abundance.clean, is.numeric)])
sparsity <- sum(count_matrix == 0) / length(count_matrix)
# 0.9520862

```



# 75% mapping rate filtering and 3% prevlance filtering on Italy
```{r}


Italy_orf.processed <- readRDS("~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/Italy/wide_rpkm_genes_75Cov.rds") %>%
                 column_to_rownames("ORFID") 
dim(Italy_orf.processed)
# 24438   132


Italy_sample_all_0 <- names(colSums(Italy_orf.processed)[colSums(Italy_orf.processed) == 0])
# [1] "NovaSeq_N982_I13323_39837_Celiac_Leonard_Stool_02_GEMM_077_12M"      
# [2] "NovaSeq_N983_I13417_39799_Leonard_Human_stool_Celiac_02_GEMM_006_60M"


Italy.orf.count <- Italy_orf.processed %>%
                   select(-all_of(Italy_sample_all_0)) 
dim(Italy.orf.count)
# 24438   130

colnames(Italy.orf.count) <- gsub("NovaSeq_N966_|NovaSeq_N978_|NovaSeq_N979_|NovaSeq_N980_|NovaSeq_N981_|NovaSeq_N982_|NovaSeq_N983_|_stats","",colnames(Italy.orf.count))
colnames(Italy.orf.count) <- str_replace_all(colnames(Italy.orf.count),"Leonard_Human_stool_Celiac","Celiac_Leonard_Stool")
colnames(Italy.orf.count) <- sapply(strsplit(colnames(Italy.orf.count),"_Stool_|_Stool_Celiac_"),"[",2)
colnames(Italy.orf.count) <- ifelse(colnames(Italy.orf.count) %like% "_6Y",gsub("_6Y","_72M",colnames(Italy.orf.count)),
                                           ifelse(colnames(Italy.orf.count) %like% "_7Y",gsub("_7Y","_84M",colnames(Italy.orf.count)),colnames(Italy.orf.count)))

Italy.orf.count.table_0.75 <- t(Italy.orf.count) 
dim(Italy.orf.count.table_0.75)
# 130 24438


Italy.orf.abundance.table_0.75 <- merge(metadata,Italy.orf.count.table_0.75,by = 0) %>% # 128 samples left
                              filter(feeding_first_year != "Unknown") %>%  # 111 samples left
                              filter(Age.at.Gluten.Introduction..months. != "Unknown") # 111 sample left
dim(Italy.orf.abundance.table_0.75)
# 111 samples x  24463 metadata+orfs
# 24438


Italy.all_0_contigs <- names(colSums(Italy.orf.abundance.table_0.75[25:24463])[colSums(Italy.orf.abundance.table_0.75[25:24463]) == 0])
# 1096 contigs become 0 through all samples after the 19 samples were removed from the above step
# so we need to remove those contigs


Italy.orf.abundance.table_0.75 <- Italy.orf.abundance.table_0.75 %>%
                            select(-all_of(Italy.all_0_contigs))
dim(Italy.orf.abundance.table_0.75)
# 111 samples x 23367 metadata+orfs
# 23342 orfs


Italy.orf.abundance.table <- Italy.orf.abundance.table_0.75 %>%
                       select(c("Row.names",26:22473)) %>%
                       column_to_rownames("Row.names") %>% 
                       t(.) %>%
                       data.frame(.)
colnames(Italy.orf.abundance.table) <- gsub("X","",colnames(Italy.orf.abundance.table))


# check prevelence filtering
prevalence <- rowSums(Italy.orf.abundance.table > 0) / ncol(Italy.orf.abundance.table)
table(prevalence > 0.03)  # 5% threshold
# FALSE  TRUE 
# 19547  2901

# Filter ORFs with prevalence > 3%
Italy.orf.abundance.clean <- Italy.orf.abundance.table[prevalence > 0.03, ]
      
dim(Italy.orf.abundance.clean)
# 2901  111

# check if there are any samples become 0 counts
names(colSums(Italy.orf.abundance.clean)[colSums(Italy.orf.abundance.clean) == 0])
# 0

dim(Italy.orf.abundance.clean)
# 2901  111


write.csv(Italy.orf.abundance.clean,"~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/Italy/Italy.orf.abundance.clean_0.75_0.03.csv",quote = FALSE,row.names = TRUE)


Italy.metadata.clean <- Italy.orf.abundance.table_0.75[1:25] %>%
                  mutate(Onset_timepoint = ifelse(Onset.Dx < 30,"pre_30","post_30")) %>%
                  column_to_rownames("Row.names")

dim(Italy.metadata.clean)
# 111  25


write.csv(Italy.metadata.clean,"~/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Virome/Orf/data/Italy/Italy.orf.metadata.clean_0.75_0.03.csv",quote = FALSE,row.names = TRUE)



# check if the column names of abundance table match the order of the row names of metadata table
all(rownames(Italy.metadata.clean) == colnames(Italy.orf.abundance.clean))
# TRUE

count_matrix <- as.matrix(Italy.orf.abundance.clean[, sapply(Italy.orf.abundance.clean, is.numeric)])
sparsity <- sum(count_matrix == 0) / length(count_matrix)
# 0.9507067

```

