#!/usr/bin/env Rscript
# Enhanced Pattern Cluster Centroids with ORF counts and slopes
# Adds informative labels to the centroid visualization
# Author: Generated by Claude
# Date: 2025-07-18

library(dplyr)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)

# Set working directory
setwd("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/compositonal_analysis")

cat("=== ENHANCED CENTROID PLOT WITH ANNOTATIONS ===\n")
cat("Starting analysis at:", format(Sys.time()), "\n\n")

# ============================================================================
# PART 1: LOAD EXISTING PATTERN DATA
# ============================================================================

cat("1. Loading pattern clustering results...\n")

# Load cluster assignments and summary
if(!file.exists("pattern_cluster_assignments.csv") || !file.exists("pattern_cluster_summary.csv")) {
  stop("Please run enhanced_pattern_clustering.R first")
}

cluster_assignments <- read.csv("pattern_cluster_assignments.csv")
cluster_summary <- read.csv("pattern_cluster_summary.csv")

# Load cluster centroids
cluster_centroids <- read.csv("pattern_cluster_centroids.csv", row.names = 1)

cat("Loaded pattern data for", length(unique(cluster_assignments$cluster)), "clusters\n")
print(cluster_summary)

# ============================================================================
# PART 2: CREATE ENHANCED LABELS WITH ORF COUNTS AND SLOPES
# ============================================================================

cat("\n2. Creating enhanced labels...\n")

# Create informative row labels
enhanced_labels <- character(nrow(cluster_summary))
for(i in 1:nrow(cluster_summary)) {
  cluster_num <- cluster_summary$cluster[i]
  n_orfs <- cluster_summary$n_orfs[i]
  slope <- round(cluster_summary$mean_slope[i], 1)
  pattern_type <- cluster_summary$dominant_pattern[i]
  
  # Create descriptive label
  enhanced_labels[i] <- paste0("Pattern ", cluster_num, 
                              " (n=", n_orfs, ", slope=", slope, ")\n",
                              toupper(substring(pattern_type, 1, 1)), 
                              substring(pattern_type, 2), " trend")
}

# Update rownames of centroids matrix
rownames(cluster_centroids) <- enhanced_labels

cat("Created enhanced labels:\n")
for(i in 1:length(enhanced_labels)) {
  cat("-", enhanced_labels[i], "\n")
}

# ============================================================================
# PART 3: GENERATE ENHANCED CENTROID PLOT
# ============================================================================

cat("\n3. Generating enhanced centroid plot...\n")

# Color palette
color_palette <- colorRampPalette(c("#2166AC", "#4393C3", "#92C5DE", "#D1E5F0", 
                                   "white", 
                                   "#FDBF6F", "#FF7F00", "#E31A1C", "#B2182B"))(100)

# Calculate breaks
max_abs_val <- max(abs(cluster_centroids), na.rm = TRUE)
break_range <- min(max_abs_val, 4)
breaks <- seq(-break_range, break_range, length.out = 101)

# Generate enhanced plot
png("enhanced_pattern_cluster_centroids.png", width = 1600, height = 1000, res = 150)

pheatmap(
  cluster_centroids,
  cluster_rows = FALSE,  # Keep original order
  cluster_cols = FALSE,
  scale = "none",
  color = color_palette,
  main = "Seven Viral Temporal Programs: Pattern Characteristics\n(Centroids show representative temporal signature for each cluster)",
  fontsize = 11,
  fontsize_row = 9,
  fontsize_col = 12,
  show_rownames = TRUE,
  show_colnames = TRUE,
  breaks = breaks,
  na_col = "grey90",
  cellwidth = 50,
  cellheight = 60,
  border_color = "white",
  angle_col = 45
)

dev.off()

cat("Generated enhanced centroid plot with ORF counts and slopes\n")

# ============================================================================
# PART 4: CREATE SUMMARY TABLE PLOT
# ============================================================================

cat("\n4. Creating summary table visualization...\n")

# Create a comprehensive summary table plot
png("pattern_summary_table.png", width = 1400, height = 800, res = 150)

par(mar = c(1, 1, 3, 1))

# Create table data
table_data <- data.frame(
  Pattern = paste0("Pattern ", cluster_summary$cluster),
  ORFs = cluster_summary$n_orfs,
  Slope = round(cluster_summary$mean_slope, 2),
  Variance = round(cluster_summary$mean_variance, 1),
  Peak_Time = round(cluster_summary$mean_peak_time, 0),
  Type = cluster_summary$dominant_pattern,
  Percentage = round(100 * cluster_summary$n_orfs / sum(cluster_summary$n_orfs), 1)
)

# Plot table
plot.new()
title("Viral Temporal Program Summary\n(Seven distinct patterns from 1,845 significant ORFs)", 
      cex.main = 1.4, font.main = 2)

# Create table layout
n_rows <- nrow(table_data) + 1  # +1 for header
n_cols <- ncol(table_data)

# Table coordinates
x_coords <- seq(0.1, 0.9, length.out = n_cols)
y_coords <- seq(0.8, 0.2, length.out = n_rows)

# Headers
headers <- c("Pattern", "# ORFs", "Slope", "Variance", "Peak Time", "Type", "% of Total")
for(j in 1:n_cols) {
  text(x_coords[j], y_coords[1], headers[j], font = 2, cex = 1.1)
}

# Data rows
for(i in 1:nrow(table_data)) {
  for(j in 1:n_cols) {
    text(x_coords[j], y_coords[i + 1], table_data[i, j], cex = 1.0)
  }
}

# Add lines for better readability
for(i in 1:(n_rows + 1)) {
  lines(c(0.05, 0.95), c(y_coords[min(i, n_rows)], y_coords[min(i, n_rows)]), lty = 1, col = "gray")
}

dev.off()

cat("Generated pattern summary table\n")

# ============================================================================
# PART 5: CREATE SLOPE RANKING PLOT
# ============================================================================

cat("\n5. Creating slope ranking visualization...\n")

png("pattern_slope_ranking.png", width = 1200, height = 800, res = 150)

# Prepare data for slope plot
slope_data <- cluster_summary
slope_data$pattern_label <- paste0("Pattern ", slope_data$cluster, "\n(n=", slope_data$n_orfs, ")")

# Create barplot
par(mar = c(8, 5, 4, 2))

bar_colors <- ifelse(slope_data$mean_slope > 0, "red", "blue")
barplot(slope_data$mean_slope,
        names.arg = slope_data$pattern_label,
        main = "Temporal Trend Slopes by Pattern\n(Positive = Increasing in CELIAC, Negative = Decreasing in CELIAC)",
        ylab = "Mean Slope",
        xlab = "",
        col = bar_colors,
        las = 2,
        cex.names = 0.9,
        cex.main = 1.2)

# Add horizontal line at zero
abline(h = 0, lty = 2, col = "black", lwd = 2)

# Add value labels on bars
for(i in 1:length(slope_data$mean_slope)) {
  y_pos <- slope_data$mean_slope[i]
  y_label <- ifelse(y_pos > 0, y_pos + 0.5, y_pos - 0.5)
  text(i * 1.2 - 0.5, y_label, round(y_pos, 1), cex = 0.9, font = 2)
}

# Add legend
legend("topright", 
       legend = c("Increasing in CELIAC", "Decreasing in CELIAC"), 
       fill = c("red", "blue"),
       cex = 1.0)

dev.off()

cat("Generated slope ranking plot\n")

# ============================================================================
# PART 6: SAVE ENHANCED RESULTS
# ============================================================================

cat("\n6. Saving enhanced results...\n")

# Save enhanced summary
enhanced_summary <- data.frame(
  cluster = cluster_summary$cluster,
  pattern_label = enhanced_labels,
  n_orfs = cluster_summary$n_orfs,
  percentage = round(100 * cluster_summary$n_orfs / sum(cluster_summary$n_orfs), 1),
  mean_slope = round(cluster_summary$mean_slope, 3),
  mean_variance = round(cluster_summary$mean_variance, 1),
  mean_peak_time = round(cluster_summary$mean_peak_time, 0),
  dominant_pattern = cluster_summary$dominant_pattern
)

write.csv(enhanced_summary, "enhanced_pattern_summary.csv", row.names = FALSE)

cat("\nEnhanced pattern visualization completed successfully!\n")
cat("Generated files:\n")
cat("- enhanced_pattern_cluster_centroids.png: Centroids with ORF counts and slopes\n")
cat("- pattern_summary_table.png: Comprehensive summary table\n")
cat("- pattern_slope_ranking.png: Slope ranking with sample sizes\n")
cat("- enhanced_pattern_summary.csv: Complete pattern characteristics\n")

cat("\nPattern Summary:\n")
for(i in 1:nrow(enhanced_summary)) {
  cat(sprintf("Pattern %d: %d ORFs (%.1f%%), slope = %.2f (%s)\n",
              enhanced_summary$cluster[i],
              enhanced_summary$n_orfs[i],
              enhanced_summary$percentage[i],
              enhanced_summary$mean_slope[i],
              enhanced_summary$dominant_pattern[i]))
}

cat("\nAnalysis completed at:", format(Sys.time()), "\n")