#!/usr/bin/env Rscript
# Improved Heatmap Analysis: Clean, informative visualizations
# Addresses issues with previous heatmap approaches
# Author: Generated by Claude
# Date: 2025-07-18

library(dplyr)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
library(limma)

# Set working directory
setwd("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/compositonal_analysis")

cat("=== IMPROVED HEATMAP ANALYSIS ===\n")
cat("Starting analysis at:", format(Sys.time()), "\n\n")

# ============================================================================
# PART 1: LOAD DATA
# ============================================================================

cat("1. Loading data...\n")

# Load limma DA results
limma_da_results <- read.csv("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/total_limma_results.csv", row.names = 1)

# Load diversity data for metadata
diversity_data <- read.csv("diversity_data_full.csv")

# Load original ORF abundance data
orf_data <- read.csv("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/orf.abundance.table_0.75_prevFiltered_temporal_cleaned_noX.csv", row.names = 1)

# Clean ORF sample names
orf_samples <- colnames(orf_data)
orf_samples_clean <- gsub("^X", "", orf_samples)
colnames(orf_data) <- orf_samples_clean

# Get significant ORFs
limma_da_results$significant <- limma_da_results$adj.P.Val < 0.05
sig_orfs <- limma_da_results[limma_da_results$significant, ]
top_n <- min(50, nrow(sig_orfs))
top_sig_orfs <- sig_orfs[order(sig_orfs$adj.P.Val), ][1:top_n, ]

cat("Using top", nrow(top_sig_orfs), "most significant ORFs\n")

# ============================================================================
# PART 2: IMPROVED PLOT 13 - LIMMA RESULTS SUMMARY
# ============================================================================

cat("\n2. Creating improved limma results visualization...\n")

# Create a comprehensive limma results plot (not a meaningless repeated heatmap)
create_limma_summary_plot <- function() {
  
  # Prepare data for visualization
  plot_data <- top_sig_orfs
  plot_data$orf_id <- rownames(plot_data)
  plot_data$rank <- 1:nrow(plot_data)
  plot_data$neg_log_padj <- -log10(plot_data$adj.P.Val)
  
  # Create a multi-panel plot
  png("limma_results_summary.png", width = 1400, height = 1000, res = 150)
  
  par(mfrow = c(2, 2), mar = c(4, 4, 3, 2))
  
  # Panel 1: LogFC distribution
  hist(plot_data$logFC, 
       breaks = 20, 
       col = "lightblue", 
       border = "darkblue",
       main = "Distribution of LogFC Values\n(Top 50 Significant ORFs)",
       xlab = "LogFC (Positive = Higher in CONTROL)",
       ylab = "Frequency")
  abline(v = median(plot_data$logFC), col = "red", lwd = 2, lty = 2)
  text(x = median(plot_data$logFC), y = max(hist(plot_data$logFC, plot = FALSE)$counts) * 0.8,
       labels = paste("Median =", round(median(plot_data$logFC), 3)), col = "red")
  
  # Panel 2: Significance vs Effect Size
  plot(plot_data$logFC, plot_data$neg_log_padj,
       pch = 16, col = "blue", cex = 0.8,
       main = "Effect Size vs Significance",
       xlab = "LogFC (Positive = Higher in CONTROL)",
       ylab = "-log10(Adjusted P-value)")
  abline(h = -log10(0.05), col = "red", lty = 2)
  text(x = min(plot_data$logFC), y = -log10(0.05) + 0.5, 
       labels = "p.adj = 0.05", col = "red")
  
  # Panel 3: Rank vs LogFC
  plot(plot_data$rank, plot_data$logFC,
       pch = 16, col = "darkgreen", cex = 0.8,
       main = "LogFC by Significance Rank",
       xlab = "Significance Rank (1 = Most Significant)",
       ylab = "LogFC")
  lines(lowess(plot_data$rank, plot_data$logFC), col = "red", lwd = 2)
  
  # Panel 4: Top 20 ORFs barplot
  top_20 <- head(plot_data, 20)
  barplot(top_20$logFC,
          names.arg = 1:20,
          col = "orange",
          border = "darkorange",
          main = "Top 20 Most Significant ORFs",
          xlab = "ORF Rank",
          ylab = "LogFC",
          las = 2)
  
  dev.off()
  
  cat("Generated improved limma results summary\n")
}

create_limma_summary_plot()

# ============================================================================
# PART 3: IMPROVED CONFOUNDER-ADJUSTED TEMPORAL HEATMAP
# ============================================================================

cat("\n3. Creating improved confounder-adjusted temporal heatmap...\n")

# Load the confounder-adjusted matrix (from previous analysis)
if(file.exists("confounder_adjusted_temporal_matrix.csv")) {
  
  adjusted_diff_matrix <- read.csv("confounder_adjusted_temporal_matrix.csv", row.names = 1)
  
  # Remove rows with insufficient data
  valid_rows <- rowSums(!is.na(adjusted_diff_matrix)) >= 3
  adjusted_diff_clean <- adjusted_diff_matrix[valid_rows, , drop = FALSE]
  
  cat("Matrix dimensions:", dim(adjusted_diff_clean), "\n")
  
  if(nrow(adjusted_diff_clean) > 0) {
    
    # IMPROVEMENT 1: Log transform to compress extreme values
    # Convert to log2 fold change to make scale more interpretable
    adjusted_diff_log <- adjusted_diff_clean
    
    # Replace NA with 0 first
    adjusted_diff_log[is.na(adjusted_diff_log)] <- 0
    
    # Apply log2 transformation for values > 0, keeping sign
    adjusted_diff_log <- sign(adjusted_diff_log) * log2(abs(adjusted_diff_log) + 1)
    
    cat("Scale after log transformation: min =", round(min(adjusted_diff_log, na.rm = TRUE), 2),
        "max =", round(max(adjusted_diff_log, na.rm = TRUE), 2), "\n")
    
    # IMPROVEMENT 2: Better color scale and breaks
    png("improved_confounder_adjusted_heatmap.png", width = 1400, height = 1600, res = 150)
    
    # Create more sensitive color palette
    color_palette <- colorRampPalette(c("#2166AC", "#4393C3", "#92C5DE", "#D1E5F0", 
                                       "white", 
                                       "#FDBF6F", "#FF7F00", "#E31A1C", "#B2182B"))(100)
    
    # Calculate symmetric breaks around zero, but more sensitive
    max_abs_val <- max(abs(adjusted_diff_log), na.rm = TRUE)
    # Use smaller range to make colors more sensitive
    break_range <- min(max_abs_val, 3)  # Cap at 3 for better color sensitivity
    breaks <- seq(-break_range, break_range, length.out = 101)
    
    pheatmap(
      adjusted_diff_log,
      cluster_rows = TRUE,
      cluster_cols = FALSE,
      scale = "none",
      color = color_palette,
      main = paste("Confounder-Adjusted Temporal Differences:", nrow(adjusted_diff_log), "ORFs\n(Log2-transformed, Red = Higher in CELIAC, Blue = Higher in CONTROL)"),
      fontsize = 8,
      fontsize_row = 6,
      fontsize_col = 10,
      show_rownames = TRUE,
      breaks = breaks,
      na_col = "grey90"
    )
    
    dev.off()
    
    cat("Generated improved confounder-adjusted heatmap with log transformation\n")
    
    # IMPROVEMENT 3: Create a focused heatmap for top patterns
    # Identify ORFs with strongest temporal patterns
    temporal_strength <- apply(adjusted_diff_log, 1, function(x) max(abs(x), na.rm = TRUE))
    top_temporal_orfs <- names(sort(temporal_strength, decreasing = TRUE))[1:min(20, length(temporal_strength))]
    
    focused_matrix <- adjusted_diff_log[top_temporal_orfs, , drop = FALSE]
    
    png("focused_temporal_patterns.png", width = 1200, height = 800, res = 150)
    
    pheatmap(
      focused_matrix,
      cluster_rows = TRUE,
      cluster_cols = FALSE,
      scale = "none",
      color = color_palette,
      main = "Top 20 ORFs with Strongest Temporal Patterns\n(Log2-transformed, confounder-adjusted)",
      fontsize = 10,
      fontsize_row = 8,
      fontsize_col = 12,
      show_rownames = TRUE,
      breaks = breaks,
      na_col = "grey90"
    )
    
    dev.off()
    
    cat("Generated focused temporal patterns heatmap\n")
    
  } else {
    cat("No valid data for improved heatmap\n")
  }
  
} else {
  cat("Confounder-adjusted matrix not found. Please run confounder_adjusted_temporal_heatmap.R first.\n")
}

# ============================================================================
# PART 4: SUMMARY AND VALIDATION
# ============================================================================

cat("\n4. Creating summary comparison...\n")

# Create a summary plot comparing different approaches
if(exists("adjusted_diff_log")) {
  
  png("heatmap_approach_comparison.png", width = 1600, height = 600, res = 150)
  
  par(mfrow = c(1, 3), mar = c(4, 4, 3, 2))
  
  # Plot 1: Original limma logFC distribution
  hist(top_sig_orfs$logFC, 
       breaks = 15, 
       col = "lightcoral", 
       main = "Original Limma LogFC\n(Static across time)",
       xlab = "LogFC",
       xlim = c(0, 0.15))
  
  # Plot 2: Raw temporal differences (problematic scale)
  if(file.exists("confounder_adjusted_temporal_matrix.csv")) {
    raw_diffs <- as.numeric(as.matrix(adjusted_diff_clean))
    raw_diffs <- raw_diffs[!is.na(raw_diffs) & is.finite(raw_diffs)]
    if(length(raw_diffs) > 0) {
      hist(raw_diffs, 
           breaks = 20, 
           col = "lightblue", 
           main = "Raw Temporal Differences\n(Problematic scale)",
           xlab = "Raw difference",
           xlim = c(-2000, 2000))
    }
  }
  
  # Plot 3: Improved log-transformed differences
  log_diffs <- as.numeric(as.matrix(adjusted_diff_log))
  log_diffs <- log_diffs[!is.na(log_diffs) & is.finite(log_diffs)]
  if(length(log_diffs) > 0) {
    hist(log_diffs, 
         breaks = 20, 
         col = "lightgreen", 
         main = "Log2-transformed Differences\n(Improved scale)",
         xlab = "Log2 difference")
  }
  
  dev.off()
  
  cat("Generated comparison plot\n")
}

cat("\nImproved heatmap analysis completed!\n")
cat("Generated files:\n")
cat("- limma_results_summary.png: Comprehensive limma results overview (replaces meaningless repeated heatmap)\n")
cat("- improved_confounder_adjusted_heatmap.png: Log-transformed temporal heatmap with better colors\n")
cat("- focused_temporal_patterns.png: Top 20 ORFs with strongest temporal patterns\n")
cat("- heatmap_approach_comparison.png: Comparison of different analytical approaches\n")

cat("\nRecommendation: Remove old plots 13, 14, 15 and use these improved visualizations instead.\n")
cat("Analysis completed at:", format(Sys.time()), "\n")