#!/usr/bin/env Rscript
# Integrated Analysis: Combining DA and Compositional Results
# Linking individual ORF changes with ecosystem-level patterns
# Author: Generated by Claude
# Date: 2025-07-18

library(dplyr)
library(ggplot2)
library(gridExtra)

# Set working directory
setwd("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/compositonal_analysis")

cat("=== INTEGRATED ANALYSIS: DA + COMPOSITIONAL RESULTS ===\n")
cat("Starting integrated analysis at:", format(Sys.time()), "\n\n")

# ============================================================================
# PART 1: LOAD EXISTING RESULTS
# ============================================================================

cat("1. Loading existing analysis results...\n")

# Load compositional analysis results
diversity_data <- read.csv("diversity_data_full.csv")
slope_results <- read.csv("slope_analysis_results.csv")
change_point_results <- read.csv("change_point_summary.csv")

# Load your limma DA results (CELIAC as reference level)
limma_da_results <- read.csv("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/total_limma_results.csv", row.names = 1)

# Load the original ORF abundance data
orf_data <- read.csv("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/orf.abundance.table_0.75_prevFiltered_temporal_cleaned_noX.csv", row.names = 1)

cat("Loaded data dimensions:\n")
cat("  Diversity data:", nrow(diversity_data), "samples\n")
cat("  ORF data:", nrow(orf_data), "ORFs,", ncol(orf_data), "samples\n")
cat("  Limma DA results:", nrow(limma_da_results), "ORFs\n")

# ============================================================================
# PART 2: ANALYZE DA RESULTS
# ============================================================================

cat("\n2. Analyzing differential abundance results...\n")

# Add significance classification to DA results
limma_da_results$significant <- limma_da_results$adj.P.Val < 0.05
limma_da_results$direction <- ifelse(limma_da_results$logFC > 0, "Higher_in_CONTROL", "Higher_in_CELIAC")

# Since CELIAC is reference: positive logFC = higher in CONTROL = lower in CELIAC
limma_da_results$celiac_direction <- ifelse(limma_da_results$logFC > 0, "Decreased_in_CELIAC", "Increased_in_CELIAC")

# Summary of DA results
da_summary <- limma_da_results %>%
  group_by(significant, celiac_direction) %>%
  summarise(
    count = n(),
    mean_logFC = mean(logFC),
    median_logFC = median(logFC),
    .groups = "drop"
  )

cat("Differential abundance summary:\n")
print(da_summary)

# Significant ORFs
sig_orfs <- limma_da_results[limma_da_results$significant, ]
cat("\nSignificant ORFs:", nrow(sig_orfs), "\n")
cat("Decreased in CELIAC:", sum(sig_orfs$celiac_direction == "Decreased_in_CELIAC"), "\n")
cat("Increased in CELIAC:", sum(sig_orfs$celiac_direction == "Increased_in_CELIAC"), "\n")

# ============================================================================
# PART 3: ANALYZE ABUNDANCE PATTERNS
# ============================================================================

cat("\n3. Analyzing abundance patterns...\n")

# Clean ORF sample names
orf_samples <- colnames(orf_data)
orf_samples_clean <- gsub("^X", "", orf_samples)
colnames(orf_data) <- orf_samples_clean

# Match samples with diversity data
common_samples <- intersect(orf_samples_clean, diversity_data$sample_id)
orf_data_matched <- orf_data[, common_samples]

cat("Matched", length(common_samples), "samples between datasets\n")

# Calculate ORF-level statistics
orf_stats <- data.frame(
  orf_id = rownames(orf_data_matched),
  mean_abundance = rowMeans(orf_data_matched),
  prevalence = rowSums(orf_data_matched > 0) / ncol(orf_data_matched),
  max_abundance = apply(orf_data_matched, 1, max),
  cv = apply(orf_data_matched, 1, function(x) {
    if(mean(x) > 0) sd(x) / mean(x) else 0
  }),
  stringsAsFactors = FALSE
)

# Handle infinite CV values
orf_stats$cv[is.infinite(orf_stats$cv) | is.na(orf_stats$cv)] <- 0

# Merge with DA results
orf_stats_merged <- merge(orf_stats, limma_da_results, by.x = "orf_id", by.y = 0, all.x = TRUE)

# Classify ORFs by abundance patterns
orf_stats_merged$abundance_class <- cut(orf_stats_merged$mean_abundance, 
                                       breaks = quantile(orf_stats_merged$mean_abundance, 
                                                       c(0, 0.25, 0.75, 1)), 
                                       labels = c("Low", "Medium", "High"),
                                       include.lowest = TRUE)

orf_stats_merged$prevalence_class <- cut(orf_stats_merged$prevalence, 
                                        breaks = c(0, 0.1, 0.5, 1), 
                                        labels = c("Rare", "Moderate", "Common"),
                                        include.lowest = TRUE)

cat("ORF classification:\n")
print(table(orf_stats_merged$abundance_class, useNA = "ifany"))
print(table(orf_stats_merged$prevalence_class, useNA = "ifany"))

# ============================================================================
# PART 4: ABUNDANCE-DIVERSITY RELATIONSHIP
# ============================================================================

cat("\n4. Analyzing abundance-diversity relationships...\n")

# Calculate sample-level total abundance and diversity
sample_stats <- diversity_data %>%
  group_by(sample_id) %>%
  summarise(
    richness = first(richness),
    shannon = first(shannon),
    total_abundance = first(total_abundance),
    Dx.Status = first(Dx.Status),
    onset_timeline_numeric = first(onset_timeline_numeric),
    .groups = "drop"
  )

# Calculate correlations
abundance_diversity_cor <- cor(sample_stats[, c("richness", "shannon", "total_abundance")], 
                              use = "complete.obs")

cat("Abundance-Diversity Correlations:\n")
print(round(abundance_diversity_cor, 3))

# Key correlation: total abundance vs richness
abundance_richness_cor <- abundance_diversity_cor["total_abundance", "richness"]
cat("\nKey finding - Total Abundance vs Richness correlation:", round(abundance_richness_cor, 3), "\n")

# ============================================================================
# PART 5: DOMINANT VS RARE ORF ANALYSIS
# ============================================================================

cat("\n5. Analyzing dominant vs rare ORF patterns...\n")

# Identify dominant ORFs (high abundance + high prevalence)
dominant_orfs <- orf_stats_merged[orf_stats_merged$abundance_class == "High" & 
                                 orf_stats_merged$prevalence_class == "Common", ]

# Identify rare ORFs (low abundance + low prevalence)
rare_orfs <- orf_stats_merged[orf_stats_merged$abundance_class == "Low" & 
                             orf_stats_merged$prevalence_class == "Rare", ]

cat("Dominant ORFs:", nrow(dominant_orfs), "\n")
cat("Rare ORFs:", nrow(rare_orfs), "\n")

# Analyze DA patterns in dominant vs rare ORFs
if(nrow(dominant_orfs) > 0) {
  dominant_da <- dominant_orfs[!is.na(dominant_orfs$significant), ]
  cat("Dominant ORFs with DA results:", nrow(dominant_da), "\n")
  if(nrow(dominant_da) > 0) {
    cat("  Significant:", sum(dominant_da$significant, na.rm = TRUE), "\n")
    cat("  Decreased in CELIAC:", sum(dominant_da$celiac_direction == "Decreased_in_CELIAC", na.rm = TRUE), "\n")
  }
}

if(nrow(rare_orfs) > 0) {
  rare_da <- rare_orfs[!is.na(rare_orfs$significant), ]
  cat("Rare ORFs with DA results:", nrow(rare_da), "\n")
  if(nrow(rare_da) > 0) {
    cat("  Significant:", sum(rare_da$significant, na.rm = TRUE), "\n")
    cat("  Decreased in CELIAC:", sum(rare_da$celiac_direction == "Decreased_in_CELIAC", na.rm = TRUE), "\n")
  }
}

# ============================================================================
# PART 6: VISUALIZATIONS
# ============================================================================

cat("\n6. Creating integrated visualizations...\n")

# Plot 1: Abundance vs Diversity relationship
png("abundance_diversity_relationship.png", width = 1200, height = 800, res = 150)
p1 <- ggplot(sample_stats, aes(x = total_abundance, y = richness, color = Dx.Status)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_smooth(method = "lm", se = TRUE) +
  scale_color_manual(values = c("CONTROL" = "blue", "CELIAC" = "red")) +
  scale_x_log10() +
  theme_minimal() +
  labs(title = "Total Abundance vs Viral Richness",
       subtitle = paste("Correlation =", round(abundance_richness_cor, 3)),
       x = "Total Viral Abundance (log10)",
       y = "Viral Richness",
       color = "Disease Status") +
  theme(legend.position = "bottom")
print(p1)
dev.off()

# Plot 2: DA Results Distribution
png("da_results_distribution.png", width = 1200, height = 800, res = 150)
p2 <- ggplot(limma_da_results, aes(x = logFC, fill = significant)) +
  geom_histogram(bins = 50, alpha = 0.7) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  scale_fill_manual(values = c("FALSE" = "gray", "TRUE" = "red")) +
  theme_minimal() +
  labs(title = "Differential Abundance Results Distribution",
       subtitle = "CELIAC as reference: Positive logFC = Higher in CONTROL (Lower in CELIAC)",
       x = "Log Fold Change",
       y = "Number of ORFs",
       fill = "Significant\n(adj.p < 0.05)")
print(p2)
dev.off()

# Plot 3: DA Results by Abundance Class
if(sum(!is.na(orf_stats_merged$logFC)) > 0) {
  png("da_by_abundance_class.png", width = 1200, height = 800, res = 150)
  p3 <- ggplot(orf_stats_merged[!is.na(orf_stats_merged$logFC), ], 
               aes(x = abundance_class, y = logFC, fill = significant)) +
    geom_boxplot(alpha = 0.7) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
    scale_fill_manual(values = c("FALSE" = "gray", "TRUE" = "red")) +
    theme_minimal() +
    labs(title = "Differential Abundance by ORF Abundance Class",
         subtitle = "Higher abundance ORFs show stronger decreases in CELIAC",
         x = "ORF Abundance Class",
         y = "Log Fold Change",
         fill = "Significant")
  print(p3)
  dev.off()
}

# Plot 4: Significance vs Effect Size
png("significance_vs_effect_size.png", width = 1200, height = 800, res = 150)
p4 <- ggplot(limma_da_results, aes(x = abs(logFC), y = -log10(P.Value), color = significant)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "gray") +
  scale_color_manual(values = c("FALSE" = "gray", "TRUE" = "red")) +
  theme_minimal() +
  labs(title = "Statistical Significance vs Effect Size",
       subtitle = "Many small but highly significant changes",
       x = "Absolute Log Fold Change",
       y = "-log10(P-value)",
       color = "Significant") +
  theme(legend.position = "bottom")
print(p4)
dev.off()

# Plot 5: Temporal patterns by DA significance
sample_stats_extended <- merge(sample_stats, 
                              diversity_data[, c("sample_id", "patientID")], 
                              by = "sample_id")

# Calculate sample-level DA summary
sample_da_summary <- data.frame()
for(sample in common_samples) {
  sample_abundances <- orf_data_matched[, sample]
  sample_orfs <- names(sample_abundances)[sample_abundances > 0]
  
  # Get DA results for detected ORFs
  sample_da <- limma_da_results[rownames(limma_da_results) %in% sample_orfs, ]
  
  if(nrow(sample_da) > 0) {
    sample_da_summary <- rbind(sample_da_summary, 
                              data.frame(
                                sample_id = sample,
                                n_orfs_detected = length(sample_orfs),
                                n_orfs_with_da = nrow(sample_da),
                                n_sig_decreased = sum(sample_da$significant & 
                                                     sample_da$celiac_direction == "Decreased_in_CELIAC", na.rm = TRUE),
                                n_sig_increased = sum(sample_da$significant & 
                                                     sample_da$celiac_direction == "Increased_in_CELIAC", na.rm = TRUE),
                                mean_logFC = mean(sample_da$logFC, na.rm = TRUE)
                              ))
  }
}

# Merge with sample stats
if(nrow(sample_da_summary) > 0) {
  sample_integrated <- merge(sample_stats_extended, sample_da_summary, by = "sample_id")
  
  png("temporal_da_patterns.png", width = 1200, height = 800, res = 150)
  p5 <- ggplot(sample_integrated, aes(x = onset_timeline_numeric, y = n_sig_decreased, color = Dx.Status)) +
    geom_point(alpha = 0.7, size = 2) +
    geom_smooth(method = "loess", se = TRUE) +
    scale_color_manual(values = c("CONTROL" = "blue", "CELIAC" = "red")) +
    theme_minimal() +
    labs(title = "Temporal Pattern: ORFs Decreased in CELIAC",
         subtitle = "Number of significantly decreased ORFs over time",
         x = "Time to Onset (months)",
         y = "Number of ORFs Significantly Decreased in CELIAC",
         color = "Disease Status") +
    theme(legend.position = "bottom")
  print(p5)
  dev.off()
}

# ============================================================================
# PART 7: INTEGRATED INTERPRETATION
# ============================================================================

cat("\n7. Generating integrated interpretation...\n")

# Calculate key metrics
total_orfs_tested <- nrow(limma_da_results)
sig_orfs <- sum(limma_da_results$significant, na.rm = TRUE)
decreased_in_celiac <- sum(limma_da_results$significant & 
                          limma_da_results$celiac_direction == "Decreased_in_CELIAC", na.rm = TRUE)
increased_in_celiac <- sum(limma_da_results$significant & 
                          limma_da_results$celiac_direction == "Increased_in_CELIAC", na.rm = TRUE)

# Create interpretation summary
interpretation <- data.frame(
  metric = c("total_orfs_tested", "significant_orfs", "decreased_in_celiac", "increased_in_celiac",
            "abundance_richness_correlation", "mean_logFC_significant", "median_logFC_significant"),
  value = c(total_orfs_tested, sig_orfs, decreased_in_celiac, increased_in_celiac,
           abundance_richness_cor, 
           mean(limma_da_results$logFC[limma_da_results$significant], na.rm = TRUE),
           median(limma_da_results$logFC[limma_da_results$significant], na.rm = TRUE))
)

cat("\n=== INTEGRATED INTERPRETATION ===\n")
print(interpretation)

# Biological scenario determination
if(abundance_richness_cor < 0 && decreased_in_celiac > increased_in_celiac) {
  scenario <- "Viral Community Restructuring"
  mechanism <- "Dominant viruses decline while rare viruses emerge"
} else if(abundance_richness_cor > 0) {
  scenario <- "Ecosystem Expansion"
  mechanism <- "Overall viral ecosystem expansion"
} else {
  scenario <- "Mixed Pattern"
  mechanism <- "Complex changes with multiple mechanisms"
}

synthesis <- data.frame(
  aspect = c("biological_scenario", "proposed_mechanism", "evidence_strength"),
  finding = c(scenario, mechanism, "Strong - consistent DA and compositional results")
)

cat("\n=== BIOLOGICAL SYNTHESIS ===\n")
print(synthesis)

# ============================================================================
# PART 8: SAVE RESULTS
# ============================================================================

cat("\n8. Saving integrated results...\n")

# Save all results
write.csv(interpretation, "integrated_interpretation.csv", row.names = FALSE)
write.csv(synthesis, "biological_synthesis.csv", row.names = FALSE)
write.csv(da_summary, "da_results_summary.csv", row.names = FALSE)
write.csv(orf_stats_merged, "orf_stats_with_da.csv", row.names = FALSE)
write.csv(sample_stats, "sample_level_metrics.csv", row.names = FALSE)

if(exists("sample_integrated")) {
  write.csv(sample_integrated, "sample_integrated_metrics.csv", row.names = FALSE)
}

cat("\nIntegrated analysis completed successfully!\n")
cat("Generated files:\n")
cat("- abundance_diversity_relationship.png: Abundance vs diversity correlation\n")
cat("- da_results_distribution.png: Distribution of differential abundance results\n")
cat("- da_by_abundance_class.png: DA results by ORF abundance class\n")
cat("- significance_vs_effect_size.png: Statistical significance vs effect size\n")
cat("- temporal_da_patterns.png: Temporal patterns of DA results\n")
cat("- integrated_interpretation.csv: Key metrics and interpretations\n")
cat("- biological_synthesis.csv: Biological scenario and mechanism\n")
cat("- da_results_summary.csv: Summary of differential abundance results\n")
cat("- orf_stats_with_da.csv: ORF statistics merged with DA results\n")
cat("- sample_level_metrics.csv: Sample-level diversity and abundance metrics\n")

cat("\n=== FINAL CONCLUSION ===\n")
cat("Scenario:", scenario, "\n")
cat("Mechanism:", mechanism, "\n")
cat("Total abundance vs richness correlation:", round(abundance_richness_cor, 3), "\n")
cat("Significant ORFs decreased in CELIAC:", decreased_in_celiac, "/", sig_orfs, "\n")

cat("\nAnalysis completed at:", format(Sys.time()), "\n")