#!/usr/bin/env Rscript
# Limma Results Heatmap: Temporal patterns of significant ORFs
# Shows logFC values across time points for significant ORFs
# Author: Generated by Claude
# Date: 2025-07-18

library(dplyr)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)

# Set working directory
setwd("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/compositonal_analysis")

cat("=== LIMMA RESULTS HEATMAP ANALYSIS ===\n")
cat("Starting heatmap analysis at:", format(Sys.time()), "\n\n")

# ============================================================================
# PART 1: LOAD DATA
# ============================================================================

cat("1. Loading data...\n")

# Load your limma DA results
limma_da_results <- read.csv("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/total_limma_results.csv", row.names = 1)

# Load diversity data for time points
diversity_data <- read.csv("diversity_data_full.csv")

# Load original ORF abundance data
orf_data <- read.csv("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/orf.abundance.table_0.75_prevFiltered_temporal_cleaned_noX.csv", row.names = 1)

# Clean ORF sample names
orf_samples <- colnames(orf_data)
orf_samples_clean <- gsub("^X", "", orf_samples)
colnames(orf_data) <- orf_samples_clean

cat("Data loaded:\n")
cat("  Limma results:", nrow(limma_da_results), "ORFs\n")
cat("  Diversity data:", nrow(diversity_data), "samples\n")
cat("  ORF abundance data:", nrow(orf_data), "ORFs,", ncol(orf_data), "samples\n")

# ============================================================================
# PART 2: PREPARE SIGNIFICANT ORFS
# ============================================================================

cat("\n2. Identifying significant ORFs...\n")

# Get significant ORFs
limma_da_results$significant <- limma_da_results$adj.P.Val < 0.05
sig_orfs <- limma_da_results[limma_da_results$significant, ]

cat("Significant ORFs:", nrow(sig_orfs), "\n")

# For visualization, let's focus on the most significant ORFs
# Sort by adjusted p-value and take top N
top_n <- min(100, nrow(sig_orfs))  # Top 100 or all if fewer
top_sig_orfs <- sig_orfs[order(sig_orfs$adj.P.Val), ][1:top_n, ]

cat("Using top", nrow(top_sig_orfs), "most significant ORFs for heatmap\n")

# ============================================================================
# PART 3: PREPARE TIME POINT DATA
# ============================================================================

cat("\n3. Preparing time point data...\n")

# Create time bins
diversity_data$time_bin <- cut(diversity_data$onset_timeline_numeric, 
                              breaks = seq(-72, 0, by = 6), 
                              include.lowest = TRUE, 
                              labels = seq(-69, -3, by = 6))

# Convert to numeric for ordering
diversity_data$time_bin_numeric <- as.numeric(as.character(diversity_data$time_bin))

# Get samples that match ORF data
common_samples <- intersect(orf_samples_clean, diversity_data$sample_id)
diversity_matched <- diversity_data[diversity_data$sample_id %in% common_samples, ]
orf_data_matched <- orf_data[, common_samples]

cat("Matched samples:", length(common_samples), "\n")
cat("Time bins available:", length(unique(diversity_matched$time_bin_numeric[!is.na(diversity_matched$time_bin_numeric)])), "\n")

# ============================================================================
# PART 4: CALCULATE ORF ABUNDANCE BY TIME AND GROUP
# ============================================================================

cat("\n4. Calculating ORF abundance patterns by time and group...\n")

# For each significant ORF, calculate mean abundance by time bin and group
calculate_orf_temporal_patterns <- function(orf_subset, abundance_data, metadata) {
  
  # Get ORF IDs that exist in abundance data
  orf_ids <- intersect(rownames(orf_subset), rownames(abundance_data))
  
  if(length(orf_ids) == 0) {
    cat("No matching ORFs found in abundance data\n")
    return(NULL)
  }
  
  cat("Processing", length(orf_ids), "ORFs\n")
  
  # Create results matrix
  time_bins <- sort(unique(metadata$time_bin_numeric[!is.na(metadata$time_bin_numeric)]))
  groups <- c("CELIAC", "CONTROL")
  
  results_list <- list()
  
  for(orf_id in orf_ids) {
    orf_abundances <- abundance_data[orf_id, ]
    
    # Merge with metadata
    orf_data_merged <- data.frame(
      sample_id = names(orf_abundances),
      abundance = as.numeric(orf_abundances),
      stringsAsFactors = FALSE
    )
    
    orf_data_merged <- merge(orf_data_merged, metadata, by = "sample_id")
    
    # Calculate mean abundance by time bin and group
    orf_summary <- orf_data_merged %>%
      filter(!is.na(time_bin_numeric)) %>%
      group_by(Dx.Status, time_bin_numeric) %>%
      summarise(
        mean_abundance = mean(abundance, na.rm = TRUE),
        n_samples = n(),
        .groups = "drop"
      ) %>%
      filter(n_samples >= 2)  # Require at least 2 samples per group per time
    
    if(nrow(orf_summary) > 0) {
      results_list[[orf_id]] <- orf_summary
    }
  }
  
  return(results_list)
}

# Calculate patterns for top significant ORFs
orf_patterns <- calculate_orf_temporal_patterns(top_sig_orfs, orf_data_matched, diversity_matched)

if(is.null(orf_patterns) || length(orf_patterns) == 0) {
  stop("No temporal patterns could be calculated")
}

cat("Successfully calculated patterns for", length(orf_patterns), "ORFs\n")

# ============================================================================
# PART 5: CREATE HEATMAP DATA MATRIX
# ============================================================================

cat("\n5. Creating heatmap data matrix...\n")

# Get all time bins represented
all_time_bins <- sort(unique(unlist(lapply(orf_patterns, function(x) x$time_bin_numeric))))
cat("Time bins for heatmap:", paste(all_time_bins, collapse = ", "), "\n")

# Create matrix for heatmap: rows = ORFs, columns = time bins
# We'll show the logFC values (from limma) as a constant across time for each ORF
# And create separate heatmaps for CELIAC vs CONTROL abundance patterns

# Method 1: Simple logFC heatmap (constant across time)
create_logfc_heatmap <- function() {
  
  # Create matrix with ORFs as rows, time bins as columns
  # Fill with logFC values (constant across time for each ORF)
  heatmap_matrix <- matrix(NA, 
                          nrow = nrow(top_sig_orfs), 
                          ncol = length(all_time_bins),
                          dimnames = list(rownames(top_sig_orfs), 
                                         paste0("T", all_time_bins)))
  
  # Fill matrix with logFC values
  for(i in 1:nrow(top_sig_orfs)) {
    orf_id <- rownames(top_sig_orfs)[i]
    logfc_value <- top_sig_orfs[orf_id, "logFC"]
    heatmap_matrix[i, ] <- logfc_value
  }
  
  return(heatmap_matrix)
}

# Method 2: Abundance difference heatmap (CELIAC - CONTROL at each timepoint)
create_abundance_diff_heatmap <- function() {
  
  # Create matrix with actual abundance differences at each time point
  heatmap_matrix <- matrix(NA, 
                          nrow = length(orf_patterns), 
                          ncol = length(all_time_bins),
                          dimnames = list(names(orf_patterns), 
                                         paste0("T", all_time_bins)))
  
  for(i in 1:length(orf_patterns)) {
    orf_id <- names(orf_patterns)[i]
    orf_data <- orf_patterns[[orf_id]]
    
    for(j in 1:length(all_time_bins)) {
      time_bin <- all_time_bins[j]
      
      # Get CELIAC and CONTROL abundances for this time bin
      celiac_abundance <- orf_data$mean_abundance[orf_data$Dx.Status == "CELIAC" & 
                                                 orf_data$time_bin_numeric == time_bin]
      control_abundance <- orf_data$mean_abundance[orf_data$Dx.Status == "CONTROL" & 
                                                  orf_data$time_bin_numeric == time_bin]
      
      # Calculate difference (CELIAC - CONTROL)
      if(length(celiac_abundance) > 0 && length(control_abundance) > 0) {
        # Log2 ratio: positive = higher in CELIAC, negative = higher in CONTROL
        if(celiac_abundance > 0 && control_abundance > 0) {
          heatmap_matrix[i, j] <- log2((celiac_abundance + 1) / (control_abundance + 1))
        }
      }
    }
  }
  
  return(heatmap_matrix)
}

# Create both types of heatmaps
logfc_matrix <- create_logfc_heatmap()
abundance_diff_matrix <- create_abundance_diff_heatmap()

cat("LogFC matrix dimensions:", dim(logfc_matrix), "\n")
cat("Abundance difference matrix dimensions:", dim(abundance_diff_matrix), "\n")

# ============================================================================
# PART 6: GENERATE HEATMAPS
# ============================================================================

cat("\n6. Generating heatmaps...\n")

# Color palette: Red = higher in CELIAC, Blue = higher in CONTROL
color_palette <- colorRampPalette(c("blue", "white", "red"))(100)

# Heatmap 1: LogFC values (constant across time)
png("limma_logfc_heatmap.png", width = 1200, height = 1600, res = 150)

# Since CELIAC is reference: positive logFC = higher in CONTROL
# We need to reverse the colors: positive (higher in CONTROL) = blue
pheatmap(
  -logfc_matrix,  # Negate to make positive values (higher in CONTROL) blue
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  scale = "none",
  color = color_palette,
  main = paste("Top", nrow(logfc_matrix), "Significant ORFs - Limma LogFC Results\n(Red = Higher in CELIAC, Blue = Higher in CONTROL)"),
  fontsize = 8,
  fontsize_row = 6,
  fontsize_col = 10,
  show_rownames = FALSE,  # Too many ORFs to show names
  breaks = seq(-max(abs(logfc_matrix), na.rm = TRUE), 
               max(abs(logfc_matrix), na.rm = TRUE), 
               length.out = 101)
)

dev.off()

# Heatmap 2: Abundance differences by time point
if(!all(is.na(abundance_diff_matrix))) {
  
  # Remove rows with all NA values
  valid_rows <- rowSums(!is.na(abundance_diff_matrix)) > 0
  abundance_diff_clean <- abundance_diff_matrix[valid_rows, , drop = FALSE]
  
  # Remove rows with too many NA values (need at least 3 non-NA values for clustering)
  enough_data <- rowSums(!is.na(abundance_diff_clean)) >= 3
  abundance_diff_clean <- abundance_diff_clean[enough_data, , drop = FALSE]
  
  if(nrow(abundance_diff_clean) > 1) {
    
    png("temporal_abundance_differences_heatmap.png", width = 1400, height = 1600, res = 150)
    
    # Replace remaining NA values with 0 for visualization
    abundance_diff_viz <- abundance_diff_clean
    abundance_diff_viz[is.na(abundance_diff_viz)] <- 0
    
    pheatmap(
      abundance_diff_viz,
      cluster_rows = TRUE,
      cluster_cols = FALSE,
      scale = "none",
      color = color_palette,
      main = paste("Temporal Abundance Differences:", nrow(abundance_diff_viz), "ORFs\n(Red = Higher in CELIAC, Blue = Higher in CONTROL)"),
      fontsize = 8,
      fontsize_row = 6,
      fontsize_col = 10,
      show_rownames = FALSE,
      breaks = seq(-max(abs(abundance_diff_viz), na.rm = TRUE), 
                   max(abs(abundance_diff_viz), na.rm = TRUE), 
                   length.out = 101)
    )
    
    dev.off()
    
    cat("Generated temporal abundance differences heatmap\n")
  } else {
    cat("Not enough valid data for temporal abundance heatmap\n")
  }
}

# Heatmap 3: Top 20 most significant ORFs with names
top_20_orfs <- head(top_sig_orfs, 20)
logfc_matrix_top20 <- logfc_matrix[1:min(20, nrow(logfc_matrix)), , drop = FALSE]

png("top20_significant_orfs_heatmap.png", width = 1200, height = 800, res = 150)

pheatmap(
  -logfc_matrix_top20,  # Negate for correct coloring
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  scale = "none",
  color = color_palette,
  main = "Top 20 Most Significant ORFs - LogFC Results\n(Red = Higher in CELIAC, Blue = Higher in CONTROL)",
  fontsize = 10,
  fontsize_row = 8,
  fontsize_col = 12,
  show_rownames = TRUE,
  breaks = seq(-max(abs(logfc_matrix_top20), na.rm = TRUE), 
               max(abs(logfc_matrix_top20), na.rm = TRUE), 
               length.out = 101)
)

dev.off()

# ============================================================================
# PART 7: SUMMARY STATISTICS
# ============================================================================

cat("\n7. Summary statistics...\n")

# Summary of logFC values
logfc_summary <- summary(top_sig_orfs$logFC)
cat("LogFC summary for top significant ORFs:\n")
print(logfc_summary)

# Count by direction
higher_in_control <- sum(top_sig_orfs$logFC > 0)
higher_in_celiac <- sum(top_sig_orfs$logFC < 0)

cat("\nDirection summary:\n")
cat("Higher in CONTROL (positive logFC):", higher_in_control, "\n")
cat("Higher in CELIAC (negative logFC):", higher_in_celiac, "\n")

# Save summary
summary_stats <- data.frame(
  metric = c("total_orfs", "higher_in_control", "higher_in_celiac", 
            "mean_logfc", "median_logfc", "max_logfc", "min_logfc"),
  value = c(nrow(top_sig_orfs), higher_in_control, higher_in_celiac,
           mean(top_sig_orfs$logFC), median(top_sig_orfs$logFC),
           max(top_sig_orfs$logFC), min(top_sig_orfs$logFC))
)

write.csv(summary_stats, "heatmap_summary_stats.csv", row.names = FALSE)

# Save the matrices for further analysis
write.csv(logfc_matrix, "logfc_heatmap_matrix.csv")
if(exists("abundance_diff_clean")) {
  write.csv(abundance_diff_clean, "abundance_diff_heatmap_matrix.csv")
}

cat("\nHeatmap analysis completed successfully!\n")
cat("Generated files:\n")
cat("- limma_logfc_heatmap.png: LogFC values for top significant ORFs\n")
cat("- temporal_abundance_differences_heatmap.png: Abundance differences by time\n")
cat("- top20_significant_orfs_heatmap.png: Top 20 ORFs with names visible\n")
cat("- heatmap_summary_stats.csv: Summary statistics\n")
cat("- logfc_heatmap_matrix.csv: Data matrix for LogFC heatmap\n")
cat("- abundance_diff_heatmap_matrix.csv: Data matrix for abundance differences\n")

cat("\nAnalysis completed at:", format(Sys.time()), "\n")