#!/usr/bin/env Rscript
# Clean sample names by removing X prefix if present
# Author: Generated by Claude
# Date: 2025-01-27

# Read the data
cat("Reading ORF abundance table...\n")
orf_data <- read.csv("/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/orf.abundance.table_0.75_prevFiltered_temporal_cleaned.csv", 
                    row.names = 1, stringsAsFactors = FALSE)

# Check current column names
cat("Original column names (first 5):", head(colnames(orf_data), 5), "\n")

# Remove X prefix from column names if present
original_names <- colnames(orf_data)
cleaned_names <- gsub("^X", "", original_names)

# Check if any changes were made
changes_made <- !identical(original_names, cleaned_names)
if(changes_made) {
  cat("Found", sum(original_names != cleaned_names), "column names with X prefix\n")
  colnames(orf_data) <- cleaned_names
  cat("Cleaned column names (first 5):", head(colnames(orf_data), 5), "\n")
  
  # Save the cleaned data
  output_file <- "/Users/leranwang/Handley Lab Dropbox/16S/Celiac/Phage/phage_detection_pipeline_new_assembly/Orf/data/total/orf.abundance.table_0.75_prevFiltered_temporal_cleaned_noX.csv"
  write.csv(orf_data, file = output_file, row.names = TRUE)
  cat("Saved cleaned data to:", output_file, "\n")
} else {
  cat("No X prefixes found in column names - data is already clean\n")
  cat("Current sample names already start with:", substr(original_names[1], 1, 10), "...\n")
}

cat("Process completed!\n")